export const ADD_TODO = "ADD_TODO";
export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";
export const DELETE_ITEM = "DELETE_ITEM";
export const IMPORTANT_ITEM = "IMPORTANT_ITEM";
export const ACTIVE_ITEM = "ACTIVE_ITEM";
export const DONE_ITEM = "DONE_ITEM";
export const GET_ALL_ITEMS = "GET_ALL_ITEMS";
export const VisibilityFilters = {
  SHOW_ALL: "SHOW_ALL",
  IMPORTANT_ITEMS: "IMPORTANT_ITEMS",
  ACTIVE_ITEMS: "ACTIVE_ITEMS",
  DONE_ITEMS: "DONE_ITEMS",
};
export const FETCH_PRODUCTS_PENDING = "FETCH_PRODUCTS_PENDING";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";
export const URL="http://localhost:3001/posts";