export const ADD_ITEM_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_ITEM_ERROR="ADD_ITEM_ERROR"

export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_ERROR="DELETE_ITEM_ERROR";

export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
export const UPDATE_TODO_ERROR="UPDATE_TODO_ERROR";

export const GET_ALL_ITEMS_SUCCESS = "GET_ALL_ITEMS_SUCCESS";
export const GET_ALL_ITEMS_ERROR = "GET_ALL_ITEMS_ERROR";

export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";
export const VisibilityFilters = {
  SHOW_ALL: "SHOW_ALL",
  IMPORTANT_ITEMS: "IMPORTANT_ITEMS",
  ACTIVE_ITEMS: "ACTIVE_ITEMS",
  DONE_ITEMS: "DONE_ITEMS",
};

export const URL="http://localhost:3001";